### ISSUE TITLE
Update the README for the repository

### ISSUE THREAD

**Issue by toddysm** [notaryproject/tuf#43]
I propose to update the README.md file for the repository with the following information:
- link to the overview of the organization
- purpose of the repository
- is it in active development or not, is it archived or not, any reasons for that
- links to relevant documentation (security audits, web site, design documents, etc.)

**Comment by FeynmanZhou** [comment]
@toddysm Considering we have proposal in https://github.com/notaryproject/.github/issues/35 to archive this repo, do you think the README needs to be updated as you suggested above?

**Comment by toddysm** [comment]
Yes, the readme needs to be updated. This repo will continue to be visible and we need to make sure that the information in the README is correct.
